# To use this file install CocoaPods.  From terminal
#    sudo gem install cocoapods
#    pod setup
# then close the Strand project in XCode and in this directory type
#    pod install
#    open Strand.xcworkspace
# From now on use Strand.xcworkspace

source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Keeper.xcodeproj'

platform :ios, '7.0' 
inhibit_all_warnings!

pod 'SAMGradientView', '~> 0.2'
pod 'CocoaLumberjack', '~> 1.9'
pod 'Firebase', '~> 2.2'
pod 'UIColor+BFPaperColors', '~> 1.3'
pod 'SVProgressHUD', '~> 1.1'
pod 'CNPGridMenu', '~> 0.2.1'
pod 'FMDB/FTS', '~> 2.4'
pod 'HockeySDK', :git => 'https://github.com/bitstadium/HockeySDK-iOS.git'
pod 'Localytics', '~> 3.0'
