# To use this file install CocoaPods.  From terminal
#    sudo gem install cocoapods
#    pod setup
# then close the Strand project in XCode and in this directory type
#    pod install
#    open Strand.xcworkspace
# From now on use Strand.xcworkspace

source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Keeper.xcodeproj'

platform :ios, '7.0' 
inhibit_all_warnings!

pod 'SAMGradientView', '~> 0.2.1'
pod 'CocoaLumberjack', '~> 1.9'
pod 'couchbase-lite-ios', '~> 1.0'
